// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stockify.Data;

#nullable disable

namespace Stockify.Data.Migrations
{
    [DbContext(typeof(StockifyContext))]
    [Migration("20250525122248_AddedStockActionCreatedAt")]
    partial class AddedStockActionCreatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stockify.Objects.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Antwerpen",
                            Name = "Liesbeth Peeters",
                            Street = "Meir",
                            ZipCode = "2000"
                        },
                        new
                        {
                            Id = 2,
                            City = "Gent",
                            Name = "Tom De Smet",
                            Street = "Veldstraat",
                            ZipCode = "9000"
                        },
                        new
                        {
                            Id = 3,
                            City = "Brugge",
                            Name = "Sofie Maes",
                            Street = "Zuidzandstraat",
                            ZipCode = "8000"
                        },
                        new
                        {
                            Id = 4,
                            City = "Leuven",
                            Name = "Bram Janssens",
                            Street = "Bondgenotenlaan",
                            ZipCode = "3000"
                        },
                        new
                        {
                            Id = 5,
                            City = "Mechelen",
                            Name = "Eline Willems",
                            Street = "Onze-Lieve-Vrouwestraat",
                            ZipCode = "2800"
                        },
                        new
                        {
                            Id = 6,
                            City = "Antwerpen",
                            Name = "Niels Vermeulen",
                            Street = "Groenplaats",
                            ZipCode = "2000"
                        },
                        new
                        {
                            Id = 7,
                            City = "Oostende",
                            Name = "Karen Van Damme",
                            Street = "Kapellestraat",
                            ZipCode = "8400"
                        },
                        new
                        {
                            Id = 8,
                            City = "Kortrijk",
                            Name = "Dries De Clercq",
                            Street = "Kortrijksesteenweg",
                            ZipCode = "8500"
                        },
                        new
                        {
                            Id = 9,
                            City = "Knokke-Heist",
                            Name = "Inge Goossens",
                            Street = "Lippenslaan",
                            ZipCode = "8300"
                        },
                        new
                        {
                            Id = 10,
                            City = "Brussel",
                            Name = "Wim Van den Broeck",
                            Street = "Rue de Namur",
                            ZipCode = "1000"
                        });
                });

            modelBuilder.Entity("Stockify.Objects.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Stockify.Objects.OrderAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderActions");
                });

            modelBuilder.Entity("Stockify.Objects.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("Stockify.Objects.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SerialNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalStock")
                        .HasColumnType("int");

                    b.Property<int>("TotalStockActions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableStock = 0,
                            Name = "Toothbrush",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 2,
                            AvailableStock = 0,
                            Name = "Schrijfbic",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 3,
                            AvailableStock = 0,
                            Name = "Notitieboekje",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 4,
                            AvailableStock = 0,
                            Name = "Afwasborstel",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 5,
                            AvailableStock = 0,
                            Name = "Wc-borstel",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 6,
                            AvailableStock = 0,
                            Name = "Flesopener",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 7,
                            AvailableStock = 0,
                            Name = "Zaklamp",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 8,
                            AvailableStock = 0,
                            Name = "Brooddoos",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 9,
                            AvailableStock = 0,
                            Name = "Koffiemok",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 10,
                            AvailableStock = 0,
                            Name = "Drinkfles",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 11,
                            AvailableStock = 0,
                            Name = "Keukenschaar",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 12,
                            AvailableStock = 0,
                            Name = "Tandenstoker",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 13,
                            AvailableStock = 0,
                            Name = "Stekkerdoos",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 14,
                            AvailableStock = 0,
                            Name = "Timer",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 15,
                            AvailableStock = 0,
                            Name = "Fietslichtje",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 16,
                            AvailableStock = 0,
                            Name = "Ovenwant",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 17,
                            AvailableStock = 0,
                            Name = "Schroevendraaier",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 18,
                            AvailableStock = 0,
                            Name = "Gsm-houder",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 19,
                            AvailableStock = 0,
                            Name = "Rekenmachine",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        },
                        new
                        {
                            Id = 20,
                            AvailableStock = 0,
                            Name = "Geurkaars",
                            SerialNumber = 0L,
                            TotalStock = 0,
                            TotalStockActions = 0
                        });
                });

            modelBuilder.Entity("Stockify.Objects.StockAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderLineId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderLineId");

                    b.HasIndex("ProductId");

                    b.ToTable("StockActions");
                });

            modelBuilder.Entity("Stockify.Objects.Order", b =>
                {
                    b.HasOne("Stockify.Objects.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Stockify.Objects.OrderAction", b =>
                {
                    b.HasOne("Stockify.Objects.Order", "Order")
                        .WithMany("Actions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Stockify.Objects.OrderLine", b =>
                {
                    b.HasOne("Stockify.Objects.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stockify.Objects.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Stockify.Objects.StockAction", b =>
                {
                    b.HasOne("Stockify.Objects.OrderLine", "OrderLine")
                        .WithMany()
                        .HasForeignKey("OrderLineId");

                    b.HasOne("Stockify.Objects.Product", "Product")
                        .WithMany("StockActions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderLine");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Stockify.Objects.Order", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("Stockify.Objects.Product", b =>
                {
                    b.Navigation("StockActions");
                });
#pragma warning restore 612, 618
        }
    }
}
