using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using Stockify.Objects;

public static class PdfGenerator
{
    static PdfGenerator()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }
    public static byte[] GenerateDeliveryPdf(Order order)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(40);

                // HEADER with "Stockify" as brand name
                page.Header().Row(row =>
                {
                    row.RelativeItem().Column(col =>
                    {
                        col.Item().Text("Stockify")
                            .FontSize(28)
                            .Bold()
                            .FontColor(Colors.Blue.Medium);
                    });

                    row.RelativeItem().AlignRight().Column(col =>
                    {
                        col.Item().Text("Overzicht bestelling")
                            .FontSize(20)
                            .Bold()
                            .FontColor(Colors.Black);
                    });
                });

                page.Content().Column(col =>
                {
                    col.Spacing(10);

                    // Customer Info
                    col.Item().Text($"Klant: {order.Customer.Name}").FontSize(16);
                    col.Item().Text($"Klantnummer: {order.Customer.Number}").FontSize(16);
                    col.Item().Text($"Datum: {DateTime.UtcNow:dd-MM-yyyy}").FontSize(16);

                    // Spacer
                    col.Item().PaddingVertical(10).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                    // Order Lines Table
                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn();
                            columns.ConstantColumn(80);
                        });

                        table.Header(header =>
                        {
                            header.Cell().Text("Product").Bold();
                            header.Cell().Text("Hoeveelheid").Bold();
                        });

                        foreach (var line in order.OrderLines)
                        {
                            table.Cell().Text(line.Product.Name);
                            table.Cell().Text(line.Quantity.ToString());
                        }
                    });
                });

                page.Footer()
                    .AlignCenter()
                    .Text("Generated by Stockify")
                    .FontSize(10)
                    .FontColor(Colors.Grey.Medium);
            });
        }).GeneratePdf();
    }
}
